import { PERMISSIONS } from "../constants/permission.constants.js";
import { ROLES } from "../constants/roles.constants.js";

export const ROLE_PERMISSIONS_MAP = {
  [ROLES.SUPER_ADMIN]: [PERMISSIONS.ALL],

  [ROLES.ADMIN]: [PERMISSIONS.ALL],

  [ROLES.USER]: [
    PERMISSIONS.USER_READ_OWN,
    PERMISSIONS.USER_UPDATE_OWN,
    PERMISSIONS.USER_DELETE_OWN,

    PERMISSIONS.PROFILE_READ_OWN,
    PERMISSIONS.PROFILE_READ_ANY,
    PERMISSIONS.PROFILE_UPDATE_OWN,

    PERMISSIONS.ADDRESS_CREATE_OWN,
    PERMISSIONS.ADDRESS_READ_OWN,
    PERMISSIONS.ADDRESS_UPDATE_OWN,
    PERMISSIONS.ADDRESS_DELETE_OWN,

    PERMISSIONS.SESSION_READ_OWN,
    PERMISSIONS.SESSION_DELETE_OWN,
    PERMISSIONS.SESSION_REVOKE_OWN,

    PERMISSIONS.ACTIVITY_READ_OWN,
    PERMISSIONS.ACTIVITY_RESET_OWN,

    PERMISSIONS.AUTH_LOGOUT_OWN,
    PERMISSIONS.AUTH_REFRESH,
  ],
};
